import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

export const formatCurrency = (amount) => `₹ ${Number(amount).toLocaleString('en-IN')}`;

const getHotelInfo = () => {
  const hotelName = localStorage.getItem('hotelName') || 'Webline PMS';
  let generatedBy = 'Admin';
  try {
    const adminInfo = JSON.parse(localStorage.getItem('adminInfo') || '{}');
    if (adminInfo.name || adminInfo.email) {
      generatedBy = adminInfo.name || adminInfo.email;
    }
  } catch (e) {
    // ignore
  }
  return { hotelName, generatedBy };
};

const getReportMetadata = (reportName, dateRange) => {
  const { hotelName, generatedBy } = getHotelInfo();
  return {
    hotelName,
    reportName,
    generatedBy,
    generatedDate: new Date().toLocaleString('en-IN'),
    filters: dateRange
  };
};

export const exportToCSV = (title, headers, rows, dateRange) => {
  const meta = getReportMetadata(title, dateRange);
  let csvContent = `Hotel:,${meta.hotelName}\n`;
  csvContent += `Report:,${meta.reportName}\n`;
  csvContent += `Generated By:,${meta.generatedBy}\n`;
  csvContent += `Generated On:,${meta.generatedDate}\n`;
  csvContent += `Filters:,${meta.filters}\n\n`;
  
  csvContent += headers.join(',') + '\n';
  rows.forEach(row => {
    const rowStr = row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',');
    csvContent += rowStr + '\n';
  });

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${title.replace(/\s+/g, '_')}_${Date.now()}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToExcel = (title, headers, rows, dateRange) => {
  const meta = getReportMetadata(title, dateRange);
  
  const wb = XLSX.utils.book_new();
  
  const wsData = [
    [meta.hotelName],
    [`Report: ${meta.reportName}`],
    [`Generated By: ${meta.generatedBy}`],
    [`Generated On: ${meta.generatedDate}`],
    [`Filters: ${meta.filters}`],
    [], 
    headers,
    ...rows
  ];
  
  const ws = XLSX.utils.aoa_to_sheet(wsData);
  
  const colWidths = headers.map(h => ({ wch: Math.max(h.length + 5, 15) }));
  ws['!cols'] = colWidths;
  
  XLSX.utils.book_append_sheet(wb, ws, 'Report');
  XLSX.writeFile(wb, `${title.replace(/\s+/g, '_')}_${Date.now()}.xlsx`);
};

export const exportToPDF = async (title, headers, rows, dateRange) => {
  const meta = getReportMetadata(title, dateRange);
  const doc = new jsPDF();
  
  let startY = 60;
  
  try {
    const logoUrl = localStorage.getItem('hotelLogo');
    if (logoUrl) {
      const img = new Image();
      img.src = logoUrl;
      await new Promise((resolve) => {
        img.onload = () => {
          doc.addImage(img, 'PNG', 14, 10, 25, 25);
          resolve();
        };
        img.onerror = resolve; // skip on error
      });
      
      doc.setFontSize(20);
      doc.setTextColor(40);
      doc.text(meta.hotelName, 45, 22);
      
      doc.setFontSize(14);
      doc.setTextColor(100);
      doc.text(meta.reportName, 45, 32);
    } else {
      doc.setFontSize(20);
      doc.setTextColor(40);
      doc.text(meta.hotelName, 14, 22);
      
      doc.setFontSize(14);
      doc.setTextColor(100);
      doc.text(meta.reportName, 14, 32);
    }
  } catch (e) {
    // fallback if logo fails
    doc.setFontSize(20);
    doc.setTextColor(40);
    doc.text(meta.hotelName, 14, 22);
    
    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text(meta.reportName, 14, 32);
  }
  
  doc.setFontSize(10);
  doc.text(`Generated By: ${meta.generatedBy}`, 14, 40);
  doc.text(`Generated On: ${meta.generatedDate}`, 14, 46);
  doc.text(`Filters: ${meta.filters}`, 14, 52);
  
  doc.autoTable({
    startY: startY,
    head: [headers],
    body: rows,
    theme: 'striped',
    headStyles: { fillColor: [56, 189, 248] },
    margin: { top: 60 },
    didDrawPage: function (data) {
      let str = "Page " + doc.internal.getNumberOfPages();
      doc.setFontSize(10);
      doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
    }
  });
  
  doc.save(`${title.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};
